name: Deploy Kero Ótica Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload Kero Ótica to DreamHost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: FTP Deploy Kero Ótica
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/USUARIO_FTP/DOMINIO_KERO_OTICA/kero_otica_LP/
          local-dir: ./kero_otica_LP/
          protocol: ftps
          port: 21
